---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Habilita repositório Nginx Amazon Linux 2
      shell: "amazon-linux-extras enable nginx1.12"
      become: yes

    - name: Instalação do Nginx
      yum:
        name: nginx
        state: latest

    - name: Instalação do PHP
      yum:
        name: '{{item}}'
        state: latest
      with_items:
        - php
        - php-common
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
        - php-fpm
    
    - name: Cópia dos arquivos de configuração do PHP
      copy:
        src: "./files/php.conf"
        dest: "/etc/php-fpm.d/www.conf"
        mode: 0644

    - name: Seta permissão nos repositórios PHP
      file:
        path: /var/lib/php
        owner: root
        group: nginx

    - name: Habilita PHP-FPM
      service: name=php-fpm enabled=yes
      become: yes
    
    - name: Inicialização do PHP-FPM
      service:
        name: php-fpm
        state: started

    - name: Cópia dos arquivos de configuração do Nginx
      copy:
        src: "./files/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644

    - name: Criação de diretórios
      file: 
        path: "/var/www/app"
        state: directory

    - name: Compactação de pacote
      local_action: shell tar -c -z -f app.zip -C ./files/php .
      become: no

    - name: Cópia do pacote compactado
      copy:
        src: "app.zip"
        dest: "/home/paschoal/app.zip"

    - name: Descompactação do pacote
      shell: "tar -xf /home/paschoal/app.zip -C /var/www/app"
    
    - name: Configuração de permissões no diretório da aplicação
      file:
        path: /var/www/app
        owner: root
        group: nginx

    - name: Atualização do arquivo de configuração do Nginx
      copy: 
        src: "./files/application.conf"
        dest: "/etc/nginx/conf.d/app.conf"
        mode: 0644

    - name: Habilita serviço Nginx
      service: name=nginx enabled=yes
      become: yes
    
    - name: Reinicia Nginx
      service:
        name: nginx
        state: restarted

    - name: Habilita repositório MariaDB no Amazon Linux 2 
      shell: "amazon-linux-extras enable mariadb10.5"
      become: yes

    - name: Instalação do MariaDB
      yum:
        name: mariadb
        state: latest

    - name: Inicialização do MariaDB
      shell: "systemctl start mariadb"
      become: yes

    - name: Habilita serviço MariaDB
      shell: "systemctl enable mariadb"
      become: yes

    - name: Recria a base de dados do MariaDB
      shell:
        cmd: |
          mariadb <<EOF
          DROP USER IF EXISTS user_manager;
          DROP DATABASE IF EXISTS user_inventory;
          CREATE DATABASE user_inventory;
          CREATE USER user_manager IDENTIFIED BY 'Qwerty123';
          GRANT ALL PRIVILEGES ON user_inventory.* TO user_manager;
          EOF
    - name: Copia os arquivos DB DDL
      copy:
        src: "./files/user_management.sql"
        dest: "/home/ec2-user/user_management.sql"
        mode: 0644
    - name: Build database tables
      shell: "mariadb user_inventory < /home/paschoal/user_management.sql"